namePrefix: prod-
commonLabels:
  variant: prod
commonAnnotations:
  note: Hello, I am prod!
resources:
- ../../base

configMapGenerator:
- name: debug-config
  behavior: create
  literals:
  - debug=off
- name: env
  behavior: replace
  literals:
  - environment=prod
- name: sql-proxy-config
  behavior: create
  literals:
  - db_connection_name=gke-stockprice:us-central1:gke-stockprice-cloudsql-prod # 事前に作成されているprod用DBのConnectionName
- name: daily-config
  behavior: create
  files:
  - daily_price_url=daily_price_url.txt
- name: growthtrend-config
  behavior: create
  literals:
  - growthtrend_targetdate=
- name: delete-gke-cluster
  behavior: replace
  literals:
  - flag=off
- name: send-slack
  behavior: replace
  literals:
  - flag=on
- name: check-holiday
  behavior: replace
  literals:
  - flag=off

secretGenerator:
- name: db-config
  behavior: replace
  files:
  - db_username=db_username.txt # echo -n "value" > fileの形で配置しておく
  - db_password=db_password.txt # echo -n "value" > fileの形で配置しておく
- name: sheetids
  behavior: create
  files:
  - holiday_sheetid=sheetid.txt # 事前に配置しておく
  - companycode_sheetid=sheetid.txt # 事前に配置しておく
  - trend_sheetid=sheetid.txt # 事前に配置しておく

- name: slack-config
  behavior: replace
  files:
  - slack_token=slack_token.txt
  - slack_channel=slack_channel.txt
- name: circleci-api-config
  behavior: replace
  files:
  - circleci_token=circleci_token.txt
