kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namePrefix: prod-
commonLabels:
  variant: prod
commonAnnotations:
  note: This is prod!
bases:
- ../../base

configMapGenerator:
- name: stockprice-configmap
  behavior: merge
  literals:
  - ENV=prod
  - DEBUG=off
  - DELETE_GKE_CLUSTER_JOB=delete_gke_cluster_by_golang
  - SEND_SLACK_MESSAGE=on
  - CHECK_DAYOFF=on
  - SCRAPE_TIMEOUT=10000
  - CALC_MOVING_TREND_CONCURRENCY=100
  - CALC_TREND_TARGETDATE=previous_date
  - MYSQLDUMP_TO_GOOGLEDRIVE=on
  - DUMP_EXECUTE_DAYS=Sunday
  - DRIVE_FOLDER_NAME=gke-stockprice-dump
  - DRIVE_FILE_MIMETYPE=text/plain
  - DRIVE_NEED_TO_BACKUP=3
  - DB_HOST=127.0.0.1
  - DB_PORT=3306
  - DB_NAME=stockprice
  - DUMP_TARGET_TABLES=daily,movingavg
  - RESTRUCTURE_EXECUTE_DATE=2021/01/17
  - RESTRUCTURE_FROM_DAILY_TABLE=daily
  - RESTRUCTURE_TO_MOVINGAVG_TABLE=movingavg_test
  - RESTRUCTURE_TO_TREND_TABLE=trend_test
  - RESTRUCTURE_FROM_DATE=2018/10/02
  - RESTRUCTURE_TO_DATE=2021/01/15
  - RESTRUCTURE_MAX_CONCURRENCY=20

  files:
  - DAILY_PRICE_URL=daily_price_url.txt

- name: sql-proxy-config
  behavior: create
  literals:
  - db_connection_name=gke-stockprice:us-central1:gke-stockprice-cloudsql-prod

secretGenerator:
- name: stockprice-secret
  behavior: merge
  files:
  - DB_USER=db_username.txt
  - DB_PASSWORD=db_password.txt
  - HOLIDAY_SHEETID=sheetid.txt
  - COMPANYCODE_SHEETID=sheetid.txt
  - TREND_SHEETID=sheetid.txt
  - STATUS_SHEETID=sheetid.txt
  - SLACK_TOKEN=slack_token.txt
  - SLACK_CHANNEL=slack_channel.txt
  - CIRCLE_API_USER_TOKEN=circleci_token.txt
  - DRIVE_PERMISSION_GMAIL=gmail.txt

patchesStrategicMerge:
- patch_cron_schedule.yaml
