apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: gke-stockprice
  labels:
    app: gke-stockprice
spec:
  # cron ref
  # https://en.wikipedia.org/wiki/Cron
  # https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/
  # https://kubernetes.io/ja/docs/concepts/workloads/controllers/cron-jobs/
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: gke-stockprice
        spec:
          containers:
          # [START proxy_container]
          - name: cloudsql-proxy
            image: us.gcr.io/cloudsql-docker/gce-proxy:1.16
            command: ["/cloud_sql_proxy",
                      "-instances=$(DB_CONNECTION_NAME)=tcp:3306",
                      "-credential_file=/credential/gke-stockprice-serviceaccount.json"]
            ports:
              - containerPort: 3306
            # [START cloudsql_security_context]
            securityContext:
              runAsUser: 2  # non-root user
              allowPrivilegeEscalation: false
            # [END cloudsql_security_context]
            env:
            - name: DB_CONNECTION_NAME
              valueFrom:
                configMapKeyRef:
                  name: sql-proxy-config
                  key: db_connection_name
            volumeMounts:
              - name: serviceaccount-volume
                mountPath: credential
                readOnly: true
          # [END proxy_container]
          - name: gke-stockprice-container
            image: us.gcr.io/gke-stockprice/gke-stockprice:latest
            imagePullPolicy: Always
            command: ["/go/bin/gke-stockprice"]
            ports:
            - containerPort: 8080
            resources:
              limits:
                cpu: "0.5"
                memory: 512Mi
              requests:
                cpu: "0.2"
                memory: 128Mi
            envFrom:
            - configMapRef:
                name: stockprice-configmap
            - secretRef:
                name: stockprice-secret
            env:
            - name: ENV_NUMBER
              valueFrom:
                configMapKeyRef:
                  name: the-map
                  key: env_number
            - name: DB_CONNECTION_NAME
              valueFrom:
                configMapKeyRef:
                  name: sql-proxy-config
                  key: db_connection_name
            volumeMounts:
              - name: serviceaccount-volume
                mountPath: credential
                readOnly: true
          volumes:
          - name: serviceaccount-volume
            secret:
              secretName: kube-gke-stockprice-serviceaccount
              items:
              - key: gke-stockprice-serviceaccount.json
                path: gke-stockprice-serviceaccount.json
          restartPolicy: Never
