kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: gke-stockprice

resources:
- cronjob.yaml
- configMap.yaml

generatorOptions:
  disableNameSuffixhash: true

# configMapGenerator:
# - name: sql-proxy-config
#   literals:
#   - db_connection_name=override.me

configMapGenerator:
# - name: stockprice-configmap
#   literals:
#   - DB_HOST=127.0.0.1
- name: sheet-config
  literals:
  - sheet-credential-path=/credential/gke-stockprice-serviceaccount.json
- name: env
  literals:
  - environment=dev
- name: delete-gke-cluster
  literals:
  - flag=off
- name: send-slack
  literals:
  - flag=off
- name: check-dayoff
  literals:
  - flag=off
- name: scrape-timeout
  literals:
  - timeout=1000
- name: moving-concurrency
  literals:
  - concurrency=3
- name: growthtrend-concurrency
  literals:
  - concurrency=3

secretGenerator:
- name: kube-gke-stockprice-serviceaccount
  files:
  - gke-stockprice-serviceaccount.json
- name: db-config
  literals:
  - db_username=root
  - db_password=
- name: slack-config
  literals:
  - slack_token=override.me
  - slack_channel=override.me
- name: circleci-api-config
  literals:
  - circleci_token=override.me
