kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: gke-stockprice

resources:
- cronjob.yaml
- configMap.yaml

generatorOptions:
  disableNameSuffixhash: true

configMapGenerator:
- name: stockprice-configmap
  literals:
  - DEBUG=on
  - DELETE_GKE_CLUSTER=off
  - SEND_SLACK_MESSAGE=off
  - CHECK_DAYOFF=off
  - SCRAPE_TIMEOUT=1000
  - CALC_MOVINGAVG_CONCURRENCY=3
  - CALC_GROWTHTREND_CONCURRENCY=3
  - GROWTHTREND_TARGETDATE=""
  - CREDENTIAL_FILEPATH=/credential/gke-stockprice-serviceaccount.json # 記載しているのは秘密鍵ファイルのパスのみ

secretGenerator:
- name: stockprice-secret
  files:
  - gke-stockprice-serviceaccount.json
  literals:
  - DB_USER=root
  - DB_PASSWORD=
