kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: gke-stockprice

resources:
- cronjob.yaml
- configMap.yaml

generatorOptions:
  disableNameSuffixhash: true

configMapGenerator:
- name: stockprice-configmap
  literals:
  - DEBUG=on
  - SEND_SLACK_MESSAGE=off
  - CHECK_DAYOFF=off
  - SCRAPE_TIMEOUT=1000
  - CALC_MOVINGAVG_CONCURRENCY=3
  - CALC_GROWTHTREND_CONCURRENCY=3
  - GROWTHTREND_TARGETDATE=""
  - CREDENTIAL_FILEPATH=/credential/gke-stockprice-serviceaccount.json

secretGenerator:
- name: kube-gke-stockprice-serviceaccount
  files:
  - gke-stockprice-serviceaccount.json
- name: stockprice-secret
  literals:
  - DB_USER=root
  - DB_PASSWORD=
