kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: gke-stockprice

resources:
- cronjob.yaml
- configMap.yaml

generatorOptions:
  disableNameSuffixhash: true

# configMapGenerator:
# - name: sql-proxy-config
#   literals:
#   - db_connection_name=override.me

configMapGenerator:
- name: sheet-config
  literals:
  - sheet-credential-path=/credential/gke-stockprice-serviceaccount.json

secretGenerator:
# - name: db-config
#   files:
#   - db_username=db_username.txt
# - name: kube-pass
#   files:
#   - password=password.txt
# - name: kube-tradederby-sheetid
#   files:
#   - tradederby_sheetid=tradederby_sheetid.txt
- name: kube-gke-stockprice-serviceaccount
  files:
  - gke-stockprice-serviceaccount.json
