namePrefix: dev-
commonLabels:
  variant: dev
commonAnnotations:
  note: This is dev!
bases:
- ../../base
patchesStrategicMerge:
- map.yaml

configMapGenerator:
- name: stockprice-configmap
  behavior: merge
  literals:
  - ENV=dev
  - MYSQLDUMP_TO_GOOGLEDRIVE=on
  - DUMP_EXECUTE_DAYS=Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday
  - DRIVE_FOLDER_NAME=gke-stockprice-dump-test
  - DRIVE_FILE_MIMETYPE=text/plain
  - DRIVE_NEED_TO_BACKUP=1
  - DB_HOST=127.0.0.1
  - DB_PORT=3306
  - DB_NAME=stockprice_dev
  - DUMP_TARGET_TABLES=daily,movingavg
  files:
  - CALC_TREND_TARGETDATE=growthtrend_targetdate.txt
  - DAILY_PRICE_URL=daily_price_url.txt

- name: sql-proxy-config
  behavior: create
  files:
  - db_connection_name=db_connection_name.txt

secretGenerator:
- name: stockprice-secret
  behavior: merge
  files:
  - HOLIDAY_SHEETID=dev_sheetid.txt
  - COMPANYCODE_SHEETID=dev_sheetid.txt
  - TREND_SHEETID=dev_sheetid.txt
  - STATUS_SHEETID=dev_sheetid.txt
  - DRIVE_PERMISSION_GMAIL=gmail.txt
